### ISSUE TITLE
README, bmake

### ISSUE THREAD

**Issue by brucelilly** [archiecobbs/libnbcompat#1]
README displayed by github is the one from pkgsrc, which might be somewhat confusing for people building elsewhere.  To have github display something else, you could rename that one and supply a README that's more informative.

Configure went fine, but "make" (or gmake or dmake, or any reasonable variant of make) fails with:
Makefile:69: *** missing separator.  Stop.
which is what usually happens with makefiles formatted to only work with bmake.
So either bmake is a requirement, or the makefile will have to be massaged (which means reading through the "Mars Attacks!"-like ac ac_ac ac_ac_ac configure scripts, figuring out what to change in autoconf/automake to get it to do the right thing in configure and Makefile.in, tweaking that, running autoconf again, yadda, yadda, yadda) [it's easier and quicker to install and run bmake].

The requirement for bmake is probably worth mentioning in a README.

**Comment by archiecobbs** [comment]
I've decided to update this so it builds using normal autotools (e.g., libtool) etc.

So hopefully all that stuff (except README) will get fixed as a side effect.

**Comment by archiecobbs** [comment]
See updated project in https://github.com/archiecobbs/libnbcompat

openSUSE build here:
  https://build.opensuse.org/package/show/devel:libraries:c_c++/libnbcompat-devel
or eventually here:
  https://build.opensuse.org/package/show/devel:libraries:c_c++/libnbcompat
