### ISSUE TITLE
bash doesn't grok "print" in generated config.status

### ISSUE THREAD

**Issue by brucelilly** [archiecobbs/libnbcompat#2]
After running autogen.sh, then configure
...
```
configure: creating ./config.status
./config.status: line 705: print: command not found
./config.status: line 705: print: command not found
./config.status: line 705: print: command not found
./config.status: line 705: print: command not found
./config.status: line 705: print: command not found
[ many more lines elided]

```
```
# head -1 config.status
#! /bin/sh

# what /bin/sh      
/bin/sh:
        Bash version 4.4.23(1) release GNU

# /bin/sh
# print foo
# sh: print: command not found
# exit
```

**Comment by archiecobbs** [comment]
I don't see that problem on openSUSE Linux 15.1. What are you running this on?

This sounds like bug in `autoconf`. What version do you have?

Check near the top of `config.status` and see if you can debug it's attempt to find an `echo(1)` command.

Here's what I see:

````bash
# Printing a long string crashes Solaris 7 /usr/bin/printf.
as_echo='\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'
as_echo=$as_echo$as_echo$as_echo$as_echo$as_echo
as_echo=$as_echo$as_echo$as_echo$as_echo$as_echo$as_echo
# Prefer a ksh shell builtin over an external printf program on Solaris,
# but without wasting forks for bash or zsh.
if test -z "$BASH_VERSION$ZSH_VERSION" \
    && (test "X`print -r -- $as_echo`" = "X$as_echo") 2>/dev/null; then
  as_echo='print -r --'
  as_echo_n='print -rn --'
elif (test "X`printf %s $as_echo`" = "X$as_echo") 2>/dev/null; then
  as_echo='printf %s\n'
  as_echo_n='printf %s'
else
  if test "X`(/usr/ucb/echo -n -n $as_echo) 2>/dev/null`" = "X-n $as_echo"; then
    as_echo_body='eval /usr/ucb/echo -n "$1$as_nl"'
    as_echo_n='/usr/ucb/echo -n'
  else
    as_echo_body='eval expr "X$1" : "X\\(.*\\)"'
    as_echo_n_body='eval
      arg=$1;
      case $arg in #(
      *"$as_nl"*)
    expr "X$arg" : "X\\(.*\\)$as_nl";
    arg=`expr "X$arg" : ".*$as_nl\\(.*\\)"`;;
      esac;
      expr "X$arg" : "X\\(.*\\)" | tr -d "$as_nl"
    '
    export as_echo_n_body
    as_echo_n='sh -c $as_echo_n_body as_echo'
  fi
  export as_echo_body
  as_echo='sh -c $as_echo_body as_echo'
fi
```

**Comment by brucelilly** [comment]
On Fri, Aug 28, 2020 at 9:56 AM Archie L. Cobbs
<notifications@github.com> wrote:
>
> I don't see that problem on openSUSE Linux 15.1. What are you running this on?

 I've been testing this on OpenSUSE "Leap" 15.2 (upgraded step-by-step from
at least 12.3, and probably earlier).

> This sounds like bug in autoconf. What version do you have?

Buried in the output of autoconf --version is
autoconf (GNU Autoconf) 2.69

> Check near the top of config.status and see if you can debug it's attempt to find an echo(1) command.

[I did say that it's easier to just install and run bmake, and that the autoconf
scripts read like the script for "Mars Attacks!", with the ac_ ac_ ac_...]

config.status probably isn't useful; it's generated to be run by configure.
config.log has some stuff buried in its 14000 lines, but it's untrustworthy,
starting near the top with:

"
It was created by libnbcompat configure 1.0.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

 $ ./configure
"

Configure was almost certainly started with
ksh93 ./configure
(because ksh93 is the only shell (aside from *very* close relatives)
that actually does what its man page documents).
Don't get me started... (unless you want to do so off-list).

Anyway, several hundred lines later there's:

"
configure:4864: checking host system type
configure:4877: result: x86_64-pc-linux-gnu
configure:4918: checking how to print strings
configure:4947: result: print -r
configure:4966: checking for a sed that does not truncate output
configure:5030: result: /usr/bin/sed
"

Now "print -r foo" will work in some shells (ksh93, pdksh, mksh, zsh),
but not on some others (unless there's a program in $PATH named
 'print"):

$ print -r foo
foo
$ whence -v print
print is a shell builtin
$ bash
$ print -r foo
# bash: print: command not found
$ exit

[And the "command-not-found" package is marked "taboo" here,
because I don't want random cruft installed every time I make
a typo or there's a bug in bash or in some script.]

Ca. line 4918 of configure, there is in fact a test for 'print -r', but it's
run by the shell running configure (ksh93) not bash (a link from
/bin/sh on OpenSUSE Linux), but configure runs config.status
with bash, so the tests should be run by configure under bash
(or config.status should be run (by configure) under the same
shell that is running configure (e.g. by sourcing config.status), or
config.status should be made more portable, e.g. by using
printf, or ...), so it is indeed a bug in autoconf.

Part of the problem seems to be that configure dicks around with
$SHELL, which it eventually uses (in a convoluted way, of course)
to run config.status.  A related issue is that $SHELL isn't always
guaranteed to be correct or directly usable (it might e.g. be "su"
or start with '-' or it might be something other than the currently
running shell (`ps -p $$ -o comm=` on any system that has any
reasonable variant of ps (which probably doesn't include the
"DOS" systems that the autoconf folks seem to be obsessed
with)).  As you can probably see, there's a lot wrong with
autoconf and the scripts that it generates and runs.  You might
be able to make it work on OpenSUSE with various available
shells (bash, dash, pdksh, mksh, ksh93, zsh (but probably not
fish, csh, or tcsh)), but then the necessary changes might break
something on those precious "DOS" systems or old Convex
systems, or HP-UX, or AIX, or Solaris, or ...  ... or on FreeBSD
with shells like oksh or bosh that aren't available in binary
packages for OpenSUSE or ...
And then there's Plan9 and rc...

Anyway, I've long ago given up trying to debug ac_ ac_ ac_ configure
scripts; there's usually a much quicker, faster, less frustrating way to
resolve problems (patch broken makefiles (in the libncompat case,
one can either run bmake (as I did) or simply comment out lines
67-69 in the Makefile (the lines beginning with a dot), in which case
just about any old make can be used), etc.).

I still think the simplest, most sustainable (e.g. if the libncompat
upstream source changes) solution is to simply note that bmake
should be used (bmake is available in source and binary
packages).  Second-best approach might be to convince the
upstream to generate more portable makefiles (N.B. changing
bmake-specific non-portable constructs into gmake-specific
non-portable constructs isn't the solution).  You're welcome to
try to get autoconf to work, but trawling through many megabytes
of cruft is near the bottom of the list of things that I'd try:

$ cat *config?* aclo* *.a[cm] autog* config/* autom*/* | wc -c
3485047

As you're using a similar system, I suspect that you may be able
to reproduce the problem by trying with the other available shells
(ksh=pdksh, mksh, ksh93, zsh).

**Comment by archiecobbs** [comment]
OK, I'll let you file a bug with the autoconf folks if you feel that's worthwhile.

Regarding bmake, this should no longer be a requirement now that we've switched to using automake.

**Comment by brucelilly** [comment]
On Fri, Aug 28, 2020 at 4:19 PM Archie L. Cobbs <notifications@github.com>
wrote:

> OK, I'll let you file a bug with the autoconf folks if you feel that's
> worthwhile.
>
> Regarding bmake, this should no longer be a requirement now that we've
> switched to using automake.
>
Because of the "print" issue, configure never gets as far as generating a
Makefile.

**Comment by archiecobbs** [comment]
Closing this issue due to lack of movement.
